name = "EindhovenLogo"
uuid = "18231132-4f0d-4a5b-8f66-ccd1a8e66870"
authors = ["matcox <matthijs.cox@gmail.com> and contributors"]
version = "0.2.1"

[deps]
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"

[compat]
Luxor = "3.7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
